version: '3'

volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: hihix/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static

  frontend:
    image: hihix/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: hihix/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles
